#pragma once

enum D3DX_VERSION_TYPE
{
	D3DX_VERSION_9 = 0,
	D3DX_VERSION_11
};

#ifndef CHECK_D3DX_VERSION
#define CHECK_D3DX_VERSION	0//D3DX_VERSION_TYPE::D3DX_VERSION_9
#endif


#if (CHECK_D3DX_VERSION == 0)//D3DX_VERSION_TYPE::D3DX_VERSION_9)
#include "D3D9Header.h"
#else
#include "D3D11Header.h"
#endif

